# Generated by Django 4.2.1 on 2024-01-13 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0064_botuser_is_admin'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportmessages',
            options={'verbose_name': 'сообщение ОС', 'verbose_name_plural': 'сообщения ОС'},
        ),
        migrations.AlterField(
            model_name='supportmessages',
            name='bot_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytlg.botuser', verbose_name='пользователь бота'),
        ),
        migrations.AlterField(
            model_name='supportmessages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания'),
        ),
        migrations.AlterField(
            model_name='supportmessages',
            name='message',
            field=models.TextField(blank=True, verbose_name='сообщение'),
        ),
    ]
