# Generated by Django 4.2.1 on 2023-06-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='Ключ')),
                ('value', models.TextField(max_length=500, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'настройка Redirect Bot',
                'verbose_name_plural': 'настройки Redirect Bot',
                'ordering': ['-id'],
            },
        ),
    ]
