# Generated by Django 4.2.1 on 2023-06-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0002_botsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=200, verbose_name='имя тематики')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
            ],
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='key',
            field=models.CharField(max_length=50, verbose_name='ключ'),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='value',
            field=models.TextField(max_length=500, verbose_name='значение'),
        ),
    ]
