# Generated by Django 4.2.1 on 2023-06-14 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0003_themes_alter_botsettings_key_alter_botsettings_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=50, verbose_name='ID канала')),
                ('channel_name', models.CharField(max_length=150, verbose_name='название канала')),
                ('channel_link', models.URLField(max_length=150, verbose_name='ссылка на канал')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytlg.themes', verbose_name='тематика канала')),
            ],
        ),
    ]
