# Generated by Django 4.2.1 on 2023-06-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0004_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='themes',
            field=models.ManyToManyField(related_name='bot_user', to='mytlg.themes', verbose_name='тематики'),
        ),
    ]
