# Generated by Django 4.2.1 on 2023-06-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0005_botuser_themes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channels',
            options={'ordering': ['-id'], 'verbose_name': 'канал', 'verbose_name_plural': 'каналы'},
        ),
        migrations.AlterModelOptions(
            name='themes',
            options={'ordering': ['id'], 'verbose_name': 'тематика', 'verbose_name_plural': 'тематики'},
        ),
    ]
