# Generated by Django 4.2.1 on 2023-06-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0007_botuser_channels_alter_channels_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='channels',
            field=models.ManyToManyField(blank=True, related_name='bot_user', to='mytlg.channels', verbose_name='каналы'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='bot_user', to='mytlg.themes', verbose_name='тематики'),
        ),
    ]
