# Generated by Django 4.2.1 on 2023-07-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0008_alter_botuser_channels_alter_botuser_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='when_send_news',
            field=models.TimeField(null=True, verbose_name='когда присылать новости'),
        ),
    ]
