# Generated by Django 4.2.1 on 2023-07-11 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0010_subthemes_alter_themes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='sub_theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mytlg.subthemes', verbose_name='подтема канала'),
        ),
        migrations.AlterField(
            model_name='channels',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mytlg.themes', verbose_name='тема канала'),
        ),
    ]
