# Generated by Django 4.2.1 on 2023-07-11 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0012_botuser_sub_themes_alter_botuser_themes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemesWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='вес')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytlg.botuser', verbose_name='юзер бота')),
                ('sub_theme', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mytlg.subthemes', verbose_name='подтема')),
                ('theme', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mytlg.themes', verbose_name='тема')),
            ],
            options={
                'verbose_name': 'вес (под)темы',
                'verbose_name_plural': 'веса (под)тем',
                'ordering': ['-id'],
            },
        ),
    ]
