# Generated by Django 4.2.1 on 2023-07-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0014_tlgaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlgaccounts',
            name='channels',
            field=models.ManyToManyField(blank=True, related_name='tlg_accounts', to='mytlg.channels', verbose_name='каналы'),
        ),
    ]
