# Generated by Django 4.2.1 on 2023-07-20 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0015_tlgaccounts_channels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botsettings',
            options={'ordering': ['-id'], 'verbose_name': 'настройка бота', 'verbose_name_plural': 'настройки бота'},
        ),
        migrations.AlterField(
            model_name='channels',
            name='sub_theme',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='mytlg.subthemes', verbose_name='подтема канала'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channels',
            name='theme',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='mytlg.themes', verbose_name='тема канала'),
            preserve_default=False,
        ),
    ]
