# Generated by Django 4.2.1 on 2023-07-20 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0017_alter_channels_sub_theme_alter_channels_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=10000, verbose_name='текст поста')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время')),
                ('is_sent', models.BooleanField(default=False, verbose_name='отправлен пользователям')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytlg.channels', verbose_name='канал')),
            ],
            options={
                'verbose_name': 'новостной пост',
                'verbose_name_plural': 'новостные посты',
                'ordering': ['-id'],
            },
        ),
    ]
