# Generated by Django 4.2.1 on 2023-07-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0019_subthemes_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='готов'),
        ),
    ]
