# Generated by Django 4.2.1 on 2023-07-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0020_channels_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='описание'),
        ),
    ]
