# Generated by Django 4.2.1 on 2023-07-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0021_channels_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='subscribers_numb',
            field=models.IntegerField(default=0, verbose_name='кол-во подписчиков'),
        ),
    ]
