# Generated by Django 4.2.1 on 2023-07-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0023_tlgaccounts_subscribed_numb_of_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='описание'),
        ),
    ]
