# Generated by Django 4.2.1 on 2023-07-28 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0024_alter_channels_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, verbose_name='название задачи')),
                ('initial_data', models.TextField(max_length=5000, verbose_name='исходные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='когда создана')),
                ('execution_result', models.TextField(max_length=5000, verbose_name='результат выполнения')),
                ('completed_at', models.DateTimeField(blank=True, verbose_name='когда завершена')),
                ('fully_completed', models.BooleanField(default=False, verbose_name='завершена полностью')),
                ('tlg_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytlg.tlgaccounts', verbose_name='аккаунт')),
            ],
            options={
                'verbose_name': 'задача аккаунту',
                'verbose_name_plural': 'задачи аккаунтам',
                'ordering': ['-id'],
            },
        ),
    ]
