# Generated by Django 4.2.1 on 2023-07-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0026_alter_accounttasks_execution_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttasks',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='когда завершена'),
        ),
    ]
