# Generated by Django 4.2.1 on 2023-09-07 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0028_newsposts_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsErrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=40, verbose_name='тип ошибки')),
                ('error_description', models.TextField(verbose_name='описание ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytlg.tlgaccounts', verbose_name='аккаунт')),
            ],
            options={
                'verbose_name': 'ошибка аккаунта',
                'verbose_name_plural': 'ошибки аккаунтов',
                'ordering': ['-id'],
            },
        ),
    ]
