# Generated by Django 4.2.1 on 2023-09-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0029_accountserrors'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlgaccounts',
            name='waiting',
            field=models.BooleanField(default=False, verbose_name='ожидание'),
        ),
    ]
