# Generated by Django 4.2.1 on 2023-09-07 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0030_tlgaccounts_waiting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, verbose_name='имя категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='themesweight',
            name='bot_user',
        ),
        migrations.RemoveField(
            model_name='themesweight',
            name='sub_theme',
        ),
        migrations.RemoveField(
            model_name='themesweight',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='sub_themes',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='themes',
        ),
        migrations.RemoveField(
            model_name='channels',
            name='sub_theme',
        ),
        migrations.RemoveField(
            model_name='channels',
            name='theme',
        ),
        migrations.DeleteModel(
            name='SubThemes',
        ),
        migrations.DeleteModel(
            name='Themes',
        ),
        migrations.DeleteModel(
            name='ThemesWeight',
        ),
        migrations.AddField(
            model_name='botuser',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='bot_user', to='mytlg.categories', verbose_name='категории'),
        ),
        migrations.AddField(
            model_name='channels',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mytlg.categories', verbose_name='категория канала'),
        ),
    ]
