# Generated by Django 4.2.1 on 2023-09-11 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0032_tlgaccounts_banned'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsSubscriptionTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'успешно завершено'), ('at_work', 'в работе'), ('error', 'завершено с ошибкой')], default='at_work', max_length=10, verbose_name='статус')),
                ('total_channels', models.IntegerField(default=0, verbose_name='всего каналов')),
                ('successful_subs', models.IntegerField(default=0, verbose_name='успешная подписка')),
                ('failed_subs', models.IntegerField(default=0, verbose_name='неудачная подписка')),
                ('action_story', models.TextField(verbose_name='история действий')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='старт')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='окончание')),
                ('initial_data', models.TextField(max_length=5000, verbose_name='исходные данные')),
                ('tlg_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytlg.tlgaccounts', verbose_name='аккаунт')),
            ],
            options={
                'verbose_name': 'задача аккаунту на подписку',
                'verbose_name_plural': 'задачи аккаунтам на подписку',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='AccountTasks',
        ),
    ]
