# Generated by Django 4.2.1 on 2023-09-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0033_accountssubscriptiontasks_delete_accounttasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountssubscriptiontasks',
            name='channels',
            field=models.ManyToManyField(blank=True, related_name='subs_task', to='mytlg.channels', verbose_name='каналы'),
        ),
    ]
