# Generated by Django 4.2.1 on 2023-09-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0034_accountssubscriptiontasks_channels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('socks5', 'socks5'), ('http', 'http'), ('https', 'https'), ('socks4', 'socks4')], max_length=6, verbose_name='протокол')),
                ('host', models.CharField(max_length=200, verbose_name='хост')),
                ('port', models.IntegerField(default=65565, verbose_name='порт')),
                ('login', models.CharField(blank=True, max_length=200, null=True, verbose_name='логин')),
                ('password', models.CharField(blank=True, max_length=200, null=True, verbose_name='пароль')),
            ],
            options={
                'verbose_name': 'прокся',
                'verbose_name_plural': 'прокси',
                'ordering': ['-id'],
            },
        ),
    ]
