# Generated by Django 4.2.1 on 2023-09-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0037_alter_tlgaccounts_proxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxys',
            name='login',
        ),
        migrations.AddField(
            model_name='proxys',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='юзернейм'),
        ),
    ]
