# Generated by Django 4.2.1 on 2023-09-18 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0038_remove_proxys_login_proxys_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=200, verbose_name='интерес')),
                ('embeddings', models.TextField(verbose_name='эмбеддинги')),
                ('when_send', models.TimeField(blank=True, null=True, verbose_name='когда присылать посты')),
                ('send_period', models.CharField(blank=True, choices=[('now', '⚡ сразу'), ('fixed_time', '🕒 фиксированное время'), ('every_time_period', '🔄 каждый промежуток времени')], null=True, verbose_name='период отправки')),
                ('last_send', models.DateTimeField(auto_now_add=True, verbose_name='крайняя отправка')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytlg.botuser', verbose_name='юзер бота')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytlg.categories', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'интерес',
                'verbose_name_plural': 'интересы',
                'ordering': ['-id'],
            },
        ),
    ]
