# Generated by Django 4.2.1 on 2023-09-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0039_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interests',
            name='send_period',
            field=models.CharField(blank=True, choices=[('now', '⚡ сразу'), ('fixed_time', '🕒 фиксированное время'), ('every_time_period', '🔄 каждый N промежуток времени')], null=True, verbose_name='период отправки'),
        ),
    ]
