# Generated by Django 4.2.1 on 2023-09-18 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0041_scheduledposts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interests',
            old_name='embeddings',
            new_name='embedding',
        ),
    ]
