# Generated by Django 4.2.1 on 2023-09-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0042_rename_embeddings_interests_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledposts',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='отправлено'),
        ),
    ]
