# Generated by Django 4.2.1 on 2023-09-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0044_newsposts_short_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsposts',
            name='post_link',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на пост'),
        ),
    ]
