# Generated by Django 4.2.1 on 2023-09-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0046_alter_botsettings_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='interests',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активен'),
        ),
    ]
