# Generated by Django 4.2.1 on 2023-09-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0047_interests_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='interests',
            name='interest_type',
            field=models.CharField(choices=[('main', 'основной'), ('networking', 'нетворкинг')], default='main', max_length=15, verbose_name='тип'),
        ),
    ]
