# Generated by Django 4.2.1 on 2023-09-20 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0048_interests_interest_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(verbose_name='ключевые слова')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytlg.botuser', verbose_name='юзер')),
            ],
            options={
                'verbose_name': 'черный список',
                'verbose_name_plural': 'черные списки',
                'ordering': ['-id'],
            },
        ),
    ]
