# Generated by Django 4.2.1 on 2023-09-25 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0049_blacklists'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledposts',
            name='interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mytlg.interests', verbose_name='интерес'),
        ),
    ]
