# Generated by Django 4.2.1 on 2023-10-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0051_scheduledposts_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledposts',
            name='selection_hash',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='хэш подборки'),
        ),
        migrations.AlterField(
            model_name='interests',
            name='interest_type',
            field=models.CharField(choices=[('main', 'основной'), ('networking', 'нетворкинг'), ('whats_new', 'что нового')], default='main', max_length=15, verbose_name='тип'),
        ),
    ]
