# Generated by Django 4.2.1 on 2023-10-04 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0052_scheduledposts_selection_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(blank=True, choices=[('like', 'лайк'), ('dislike', 'дизлайк')], max_length=20, null=True, verbose_name='реакция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='изменена')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytlg.botuser', verbose_name='юзер')),
                ('news_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytlg.newsposts', verbose_name='пост')),
            ],
            options={
                'verbose_name': 'реакция',
                'verbose_name_plural': 'реакции',
                'ordering': ['-id'],
            },
        ),
    ]
