# Generated by Django 4.2.1 on 2023-10-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0054_alter_reactions_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxys',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='proxys',
            name='protocol_type',
            field=models.BooleanField(default=False, verbose_name='IPv6'),
        ),
    ]
