# Generated by Django 4.2.1 on 2023-11-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0055_proxys_description_proxys_protocol_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='source_tag',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тег источника'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения пользователя'),
        ),
    ]
