# Generated by Django 4.2.1 on 2023-11-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0056_botuser_source_tag_botuser_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlgaccounts',
            name='for_search',
            field=models.BooleanField(default=False, verbose_name='Аккаунт используется для поиска каналов'),
        ),
    ]
