# Generated by Django 4.2.1 on 2023-11-23 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0057_tlgaccounts_for_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountssubscriptiontasks',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mytlg.botuser', verbose_name='Привязана к пользователю'),
        ),
    ]
