# Generated by Django 4.2.1 on 2023-11-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0058_accountssubscriptiontasks_assigned_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='custom_channels',
            field=models.JSONField(blank=True, default=list, verbose_name='Добавленные пользователем каналы'),
        ),
    ]
