# Generated by Django 4.2.1 on 2023-11-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0059_botuser_custom_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsposts',
            name='from_custom_channel',
            field=models.BooleanField(default=False, verbose_name='из кастомного канала юзера'),
        ),
    ]
