# Generated by Django 4.2.1 on 2023-12-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0060_newsposts_from_custom_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='only_custom_channels',
            field=models.BooleanField(default=False, verbose_name='только со своих каналов'),
        ),
    ]
