# Generated by Django 4.2.1 on 2023-12-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0062_channels_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlgaccounts',
            name='description',
            field=models.CharField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='tlgaccounts',
            name='json_data',
            field=models.JSONField(blank=True, null=True, verbose_name='json данные аккаунта'),
        ),
        migrations.AlterField(
            model_name='tlgaccounts',
            name='subscribed_numb_of_channels',
            field=models.IntegerField(default=0, verbose_name='кол-во подписок'),
        ),
    ]
