# Generated by Django 4.2.1 on 2024-01-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0063_tlgaccounts_description_tlgaccounts_json_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='админ'),
        ),
    ]
