# Generated by Django 4.2.1 on 2024-01-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0063_tlgaccounts_description_tlgaccounts_json_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxys',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='код страны'),
        ),
    ]
