# Generated by Django 4.2.1 on 2024-01-22 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0064_botuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxys',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='код страны'),
        ),
        migrations.AddField(
            model_name='proxys',
            name='external_proxy_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Внешний прокси ID'),
        ),
        migrations.CreateModel(
            name='CustomChannelsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_send', models.TimeField(blank=True, null=True, verbose_name='когда присылать посты')),
                ('send_period', models.CharField(blank=True, choices=[('now', '⚡ сразу'), ('fixed_time', '🕒 фиксированное время'), ('every_time_period', '🔄 каждый N промежуток времени')], null=True, verbose_name='период отправки')),
                ('last_send', models.DateTimeField(auto_now_add=True, verbose_name='крайняя отправка')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytlg.botuser', verbose_name='юзер бота')),
            ],
            options={
                'verbose_name': 'настройка кастомных каналов',
                'verbose_name_plural': 'настройки кастомных каналов',
                'ordering': ['id'],
            },
        ),
    ]
