# Generated by Django 4.2.1 on 2024-01-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0064_proxys_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxys',
            name='external_proxy_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Внешний прокси ID'),
        ),
    ]
