# Generated by Django 4.2.1 on 2024-01-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0065_proxys_country_code_proxys_external_proxy_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='share_link',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка для поделиться'),
        ),
    ]
