# Generated by Django 4.2.1 on 2024-01-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0064_botuser_is_admin'),
        ('mytlg', '0065_proxys_external_proxy_id'),
    ]

    operations = [
    ]
