# Generated by Django 4.2.1 on 2024-01-29 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0067_botuser_number_of_attracted_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botuser',
            old_name='share_link',
            new_name='shared_link',
        ),
    ]
