# Generated by Django 4.2.1 on 2024-02-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytlg', '0068_rename_share_link_botuser_shared_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменен')),
            ],
        ),
    ]
